name: Legacy CI (disabled)

on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Use .github/workflows/main.yml for CI. This legacy workflow is disabled."
